### ISSUE TITLE
Storage Facedes not working

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-flysystem-cloudinary#2]
- [ ] allFiles()
- [ ] files()
- [ ] directories() 
- [ ] get()

<img width="2215" alt="CleanShot 2021-06-23 at 23 35 39@2x" src="https://user-images.githubusercontent.com/10268813/123171182-be144f00-d47b-11eb-8200-420af7b7ccce.png">

<img width="1232" alt="CleanShot 2021-06-23 at 23 40 02@2x" src="https://user-images.githubusercontent.com/10268813/123171628-5c081980-d47c-11eb-9308-8153c4a8f56e.png">

<img width="645" alt="CleanShot 2021-06-23 at 23 37 27@2x" src="https://user-images.githubusercontent.com/10268813/123171361-003d9080-d47c-11eb-83db-07a53222a711.png">

### allDirectories()
- [ ] allDirectories() // Returns wrong results 
- [ ] expected only assets

<img width="1230" alt="CleanShot 2021-06-23 at 23 46 26@2x" src="https://user-images.githubusercontent.com/10268813/123172296-3e877f80-d47d-11eb-97bf-7fac4340c81f.png">

**env**

```
CLOUDINARY_CLOUD_NAME=codebar-solutions-ag
CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=
CLOUDINARY_FOLDER=www-codebar-ch
```

**Comment by SuddenlyRust** [comment]
We got problems with the folder prefix. This is now fixed in the newest release https://github.com/codebar-ag/laravel-flysystem-cloudinary/releases/tag/1.0.2
