### ISSUE TITLE
Get File is not working

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-flysystem-cloudinary#3]
<img width="1304" alt="CleanShot 2021-06-25 at 18 44 24@2x" src="https://user-images.githubusercontent.com/10268813/123458456-5ed24e00-d5e5-11eb-96fd-dbcd034d0896.png">

https://res.cloudinary.com/codebar-solutions-ag/raw/upload/application-staging-vanta-ch/assets/mix-manifest.json

<img width="1112" alt="CleanShot 2021-06-25 at 18 44 32@2x" src="https://user-images.githubusercontent.com/10268813/123458485-6560c580-d5e5-11eb-931e-5aab49e0ad9a.png">

Fehlt da der zweite ://?
![CleanShot 2021-06-25 at 18 45 02@2x](https://user-images.githubusercontent.com/10268813/123458575-7a3d5900-d5e5-11eb-9522-53256a84fd68.png)

**Comment by SuddenlyRust** [comment]
Der Filedriver funktioniert nur mit relativen Pfaden. Versuch es mal mit `Storage::get('assets/mix-manifest.json');`.
Wenn du den ganzen Pfad hast, kannst du es mit `file_get_contents($path)` versuchen.
