### ISSUE TITLE
Storage::delete not working

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-flysystem-cloudinary#4]
<img width="1313" alt="CleanShot 2021-06-29 at 18 21 21@2x" src="https://user-images.githubusercontent.com/10268813/123833673-e3371080-d906-11eb-8910-e1693d8679f7.png">

**Comment by SuddenlyRust** [comment]
For every resource type we need to make a new request to the API. This is fixed with the [v1.0.3](https://github.com/codebar-ag/laravel-flysystem-cloudinary/releases/tag/1.0.3)

Previously it did only work for images. Now it will delete all assets.
