### ISSUE TITLE
Laravel Upgrade from 8.75 to 10.10

### ISSUE THREAD

**Issue by Mubassir-developer** [codebar-ag/laravel-flysystem-cloudinary#43]
I have created a new project with the latest version and then tried to install the required packages in that new project. and codebar-ag/laravel-flysystem-cloudinary is throwing an error. Please let me know what I should do.

`
$ composer require codebar-ag/laravel-flysystem-cloudinary
Cannot use codebar-ag/laravel-flysystem-cloudinary's latest version v3.1.0 as it requires php ^8.2 which is not satisfied by your platform.
./composer.json has been updated
Running composer update codebar-ag/laravel-flysystem-cloudinary
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codebar-ag/laravel-flysystem-cloudinary[0.0.0, ..., 0.3.0, 1.0.0, ..., 1.0.4] require illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - codebar-ag/laravel-flysystem-cloudinary 1.1.0 requires illuminate/contracts ^8.0 || ^9.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.15] but these were not loaded, likely because it conflicts with another require.
    - codebar-ag/laravel-flysystem-cloudinary[2.0.0, ..., 2.0.3] require illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.15] but these were not loaded, likely because it conflicts with another require.
    - codebar-ag/laravel-flysystem-cloudinary[2.1.0, ..., 2.20, 3.0, ..., v3.1.0] require php ^8.2 -> your php version (8.1.22) does not satisfy that requirement.
    - Root composer.json requires codebar-ag/laravel-flysystem-cloudinary * -> satisfiable by codebar-ag/laravel-flysystem-cloudinary[0.0.0, 0.1.0, 0.2.0, 0.3.0, 1.0.0, ..., 1.1.0, 2.0.0, ..., 2.20, 3.0, 3.0.1, v3.1.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require codebar-ag/laravel-flysystem-cloudinary:*" to figure out if any version is installable, or "composer require codebar-ag/laravel-flysystem-cloudinary:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Comment by RhysLees** [comment]
As stated in the error message `"Cannot use codebar-ag/laravel-flysystem-cloudinary's latest version v3.1.0 as it requires php ^8.2 which is not satisfied by your platform."` It looks as if you are using a version of php lower than 8.2 which this package requires.

Ensure your `composer.json` you have `"php": "^8.2",` and the version of php-fpm you use is 8.2.
You can check this by running the command `php -v`.

Then follow the install steps again.


Let me know if this solves your issue.

**Comment by StanBarrows** [comment]
@Mubassir-developer 

<img width="890" alt="CleanShot 2023-09-08 at 23 53 00@2x" src="https://github.com/codebar-ag/laravel-flysystem-cloudinary/assets/10268813/9b525c7b-b9ec-42d3-8f28-1e867ae74bc5">

**Comment by Mubassir-developer** [comment]
I was using php8.1.
Issue resolve with php8.2
