### ISSUE TITLE
[Bug]: Unable to retrieve an uploaded file in Laravel 11

### ISSUE THREAD

**Issue by hamidroohani** [codebar-ag/laravel-flysystem-cloudinary#61]
### What happened?

When you define a folder in `filesystem.php` the file will upload to this dir correctly.
But if you want to call the `exists` method on `Storage` you must add the folder in hard code for this method
And the second problem is when you want to call the `url` method on `Storage`, you must delete the folder and put dubble file extension.

`\Illuminate\Support\Facades\Storage::disk('cloudinary')->exists("mc/01J493QRS7S4AWYB3V522JN48B.jpg");`

`\Illuminate\Support\Facades\Storage::disk('cloudinary')->url("01J493QRS7S4AWYB3V522JN48B.jpg.jpg");`

### Package Version

4.2

### PHP Version

8.3

### Laravel Version

11.0.0

### Which operating systems does with happen with?

macOS, Linux

**Comment by RhysLees** [comment]
Looking into this issue now

**Comment by RhysLees** [comment]
@hamidroohani 

>When you define a folder in filesystem.php the file will upload to this dir correctly.
>But if you want to call the exists method on Storage you must add the folder in hard code for this method

Can you please share your filesystem settings for cloudinary.

I've tested exists locally using the CLOUDINARY_FOLDER and it returns true,

```diff
- Ensure you remove any sensitive information
```

> And the second problem is when you want to call the url method on Storage, you must delete the folder and put dubble file extension.

This is intended, the `01J493QRS7S4AWYB3V522JN48B.jpg` would be the public_id in cloudinary.
![image](https://github.com/user-attachments/assets/eb3655ee-fe82-4410-800b-9d5a2f91ab27)


The second `.jpg` is the file type you wish to return, you can change the second extension to `.webp` for example.
https://cloudinary.com/documentation/image_transformations#delivering_in_a_different_format

Please see the following for an in-detail explanation: https://github.com/codebar-ag/laravel-flysystem-cloudinary/issues/56#issuecomment-2025046863

**Comment by StanBarrows** [comment]
https://github.com/codebar-ag/laravel-flysystem-cloudinary/releases/tag/v4.2.1
