### ISSUE TITLE
[Bug]: Not compatible with filament

### ISSUE THREAD

**Issue by hamidroohani** [codebar-ag/laravel-flysystem-cloudinary#63]
### What happened?

```
FileUpload::make('logo')
    ->disk('cloudinary')
    ...
```

The file will upload successfully, but it doesn't appear in the table, and I also in the edit page occur an error: `Unable to retrieve the file_size for file at location: 01J4GR1EFN8ERFPGD52SJY37S4.jpg`

![Screenshot 2024-08-05 at 09 49 28](https://github.com/user-attachments/assets/f46dfb5e-1f1c-4edd-a605-7add5a2b113b)

### Package Version

4.2.1

### PHP Version

8.3

### Laravel Version

11.0.0

### Which operating systems does with happen with?

macOS, Linux

**Comment by StanBarrows** [comment]
Hey @hamidroohani 

I'm unaware of how the file handling works within the Filament; I assume you need to create a custom Filament Field for this, as we made a Field Component for Laravel Nova.

https://github.com/codebar-ag/laravel-flysystem-cloudinary-nova

**Comment by RhysLees** [comment]
https://github.com/codebar-ag/laravel-flysystem-cloudinary?tab=readme-ov-file#-file-extension-problem

From first looks without testing, it seems your cloudinary file id is likley `01J4GR1EFN8ERFPGD52SJY37S4.jpg` you should not upload files with the extension on the end as specified in the documentation linked above.

I would think you need to use something like the following in Filament to get this behaviour to work:
https://filamentphp.com/docs/3.x/forms/fields/file-upload#generating-custom-file-names
